### ISSUE TITLE
你好~

### ISSUE THREAD

**Issue by Kgym-Hina** [CYRO4S/Automator#2]
我觉得新的MD设计是很不错，但是明显旧版本要清晰许多（思路），能不能在简化的过程中保留一个以前版本的模式呢

**Comment by playercatboy** [comment]
我并没有觉得更换 UI 是一种简化。。  
相较之前的版本只是按钮的位置改变了，按钮配的说明被移到了 tooltip 中。  
先前版本最大的问题是使用了标签页，添加功能需要经常更换标签页。 而改动后把所有需要的功能全部集成在了一个工具栏中。 
  
鉴于新 UI 并未包含功能性改进，你仍然可以使用旧版。但是改进新版，我恐有心无力，但欢迎贡献😺
